openapi: 3.1.0
info:
  title: Ad Manager Admin API
  version: v1
  description: API for Platform Admin Portal functionalities, such as user management and system settings.
  contact:
    name: Ad Manager Platform Team
    email: platform-team@admanager.example.com

servers:
  - url: https://{stage}.api.admanager.example.com/admin/v1
    variables:
      stage:
        default: dev
        description: The deployment stage (e.g., dev, prod).
  - url: http://localhost:3000/admin/v1 # For local development if proxied
    description: Local development server

tags:
  - name: User Management
    description: Operations related to managing platform users and merchants.
  - name: Platform Settings
    description: Configuration of global platform settings.
  - name: System Health
    description: Endpoints for monitoring system health.

paths:
  /users:
    get:
      tags:
        - User Management
      summary: List all users
      description: Retrieves a paginated list of all users on the platform. (Admin access required)
      operationId: listAllUsers
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - $ref: './shared-components.yaml#/components/parameters/CorrelationIdHeader'
      security:
        - JWTBearerAuth: [] # Scope for admin might be checked in authorizer/backend
      responses:
        '200':
          description: A paginated list of users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/PlatformUser' # Defined below or in shared
                  pageInfo:
                    $ref: './shared-components.yaml#/components/schemas/PaginationInfo'
        '401':
          $ref: './shared-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './shared-components.yaml#/components/responses/ForbiddenError'
        '500':
          $ref: './shared-components.yaml#/components/responses/InternalServerError'

  /users/{userId}:
    get:
      tags:
        - User Management
      summary: Get user by ID
      description: Retrieves details for a specific user. (Admin access required)
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - $ref: './shared-components.yaml#/components/parameters/CorrelationIdHeader'
      security:
        - JWTBearerAuth: []
      responses:
        '200':
          description: User details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformUser'
        '401':
          $ref: './shared-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './shared-components.yaml#/components/responses/ForbiddenError'
        '404':
          $ref: './shared-components.yaml#/components/responses/NotFoundError'
        '500':
          $ref: './shared-components.yaml#/components/responses/InternalServerError'

  /platform-settings:
    get:
      tags:
        - Platform Settings
      summary: Get all platform settings
      description: Retrieves all current platform configuration settings. (Admin access required)
      operationId: getPlatformSettings
      parameters:
        - $ref: './shared-components.yaml#/components/parameters/CorrelationIdHeader'
      security:
        - JWTBearerAuth: []
      responses:
        '200':
          description: Platform settings.
          content:
            application/json:
              schema:
                type: object # Define schema for platform settings
                properties:
                  settingKey1:
                    type: string
                  settingKey2:
                    type: boolean
        '401':
          $ref: './shared-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './shared-components.yaml#/components/responses/ForbiddenError'
        '500':
          $ref: './shared-components.yaml#/components/responses/InternalServerError'
    put:
      tags:
        - Platform Settings
      summary: Update platform settings
      description: Updates one or more platform configuration settings. (Admin access required)
      operationId: updatePlatformSettings
      parameters:
        - $ref: './shared-components.yaml#/components/parameters/CorrelationIdHeader'
      requestBody:
        description: Settings to update.
        required: true
        content:
          application/json:
            schema:
              type: object # Define schema for updatable platform settings
              properties:
                settingKey1:
                  type: string
      security:
        - JWTBearerAuth: []
      responses:
        '200':
          description: Settings updated successfully.
        '400':
          $ref: './shared-components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './shared-components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './shared-components.yaml#/components/responses/ForbiddenError'
        '500':
          $ref: './shared-components.yaml#/components/responses/InternalServerError'

components:
  schemas:
    PlatformUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        roles:
          type: array
          items:
            type: string
        merchantId: # If user is associated with a specific merchant
          type: string
          format: uuid
          nullable: true
        status:
          type: string
          enum: [ACTIVE, INACTIVE, SUSPENDED]
      required:
        - id
        - email
        - roles
        - status

    ErrorResponse:
      $ref: './shared-components.yaml#/components/schemas/ErrorResponse'
    PaginationInfo:
      $ref: './shared-components.yaml#/components/schemas/PaginationInfo'

  securitySchemes:
    JWTBearerAuth:
      $ref: './shared-components.yaml#/components/securitySchemes/JWTBearerAuth'