export enum AuditAction {
  // User Management
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_ROLE_ASSIGNED = 'USER_ROLE_ASSIGNED',
  USER_ROLE_REMOVED = 'USER_ROLE_REMOVED',
  USER_CREATED = 'USER_CREATED', // Admin creating user
  USER_UPDATED = 'USER_UPDATED', // Admin updating user
  USER_DELETED = 'USER_DELETED', // Admin deleting user
  
  // Campaign Management
  CAMPAIGN_CREATED = 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED',
  CAMPAIGN_DELETED = 'CAMPAIGN_DELETED',
  CAMPAIGN_STATUS_CHANGED = 'CAMPAIGN_STATUS_CHANGED',
  AD_SET_CREATED = 'AD_SET_CREATED',
  // ... other campaign actions

  // Product Catalog
  PRODUCT_CATALOG_CREATED = 'PRODUCT_CATALOG_CREATED',
  PRODUCT_CATALOG_UPDATED = 'PRODUCT_CATALOG_UPDATED',
  PRODUCT_CATALOG_DELETED = 'PRODUCT_CATALOG_DELETED',
  PRODUCT_CATALOG_SYNC_STARTED = 'PRODUCT_CATALOG_SYNC_STARTED',
  PRODUCT_CATALOG_SYNC_COMPLETED = 'PRODUCT_CATALOG_SYNC_COMPLETED',
  PRODUCT_CATALOG_SYNC_FAILED = 'PRODUCT_CATALOG_SYNC_FAILED',

  // Security
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_DELETED = 'API_KEY_DELETED',
  SECURITY_POLICY_UPDATED = 'SECURITY_POLICY_UPDATED',
  PERMISSION_DENIED_ACCESS_ATTEMPT = 'PERMISSION_DENIED_ACCESS_ATTEMPT',

  // System & Configuration
  SYSTEM_CONFIG_UPDATED = 'SYSTEM_CONFIG_UPDATED',
  FEATURE_FLAG_TOGGLED = 'FEATURE_FLAG_TOGGLED',
  MAINTENANCE_MODE_ACTIVATED = 'MAINTENANCE_MODE_ACTIVATED',
  MAINTENANCE_MODE_DEACTIVATED = 'MAINTENANCE_MODE_DEACTIVATED',
  
  // Billing & Subscription
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILURE = 'PAYMENT_FAILURE',

  // Data Governance
  DSR_REQUEST_RECEIVED = 'DSR_REQUEST_RECEIVED',
  DSR_REQUEST_PROCESSED = 'DSR_REQUEST_PROCESSED', // e.g., data access, erasure
  CONSENT_GIVEN = 'CONSENT_GIVEN',
  CONSENT_WITHDRAWN = 'CONSENT_WITHDRAWN',
  DATA_EXPORTED = 'DATA_EXPORTED',
  DATA_DELETED_BY_RETENTION = 'DATA_DELETED_BY_RETENTION',

  // Generic
  RESOURCE_CREATED = 'RESOURCE_CREATED',
  RESOURCE_UPDATED = 'RESOURCE_UPDATED',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  PENDING = 'PENDING', // For actions that might be async
}