export enum ErrorCodes {
  // General HTTP
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  
  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR', // Generic validation
  INVALID_INPUT_FORMAT = 'INVALID_INPUT_FORMAT',

  // Domain Specific (Examples)
  CAMPAIGN_BUDGET_EXCEEDED = 'CAMPAIGN_BUDGET_EXCEEDED',
  AD_NETWORK_API_ERROR = 'AD_NETWORK_API_ERROR',
  PRODUCT_CATALOG_SYNC_FAILED = 'PRODUCT_CATALOG_SYNC_FAILED',

  // Configuration
  CONFIG_VALUE_MISSING = 'CONFIG_VALUE_MISSING',
  
  // Add more as needed
}