import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { CurrentPeriodMetricsDto } from './current-period-metrics.dto';
import { Type } from 'class-transformer';
import { ValidateNested } from 'class-validator';


export class AffiliatePerformanceResponseDto {
  @ApiProperty({
    description: 'Total clicks generated by the affiliate.',
    example: 5000,
  })
  clicks: number;

  @ApiProperty({
    description: 'Total conversions attributed to the affiliate.',
    example: 250,
  })
  conversions: number;

  @ApiProperty({
    description: 'Overall conversion rate (conversions/clicks).',
    example: 0.05, // 5%
  })
  conversionRate: number;

  @ApiProperty({
    description: 'Total commissions earned by the affiliate (lifetime or selected period).',
    example: 2500.00,
  })
  earnedCommissions: number;

  @ApiProperty({
    description: 'Commissions earned but not yet paid out.',
    example: 350.50,
  })
  pendingCommissions: number;

  @ApiProperty({
    description: 'Total commissions already paid out to the affiliate.',
    example: 2149.50,
  })
  paidCommissions: number;

  @ApiPropertyOptional({
    description: 'Estimated date for the next payout.',
    example: '2023-08-01T00:00:00.000Z',
  })
  nextPayoutDate?: Date;

  @ApiProperty({
    description: 'Performance metrics for the current (or most recent) period.',
    type: () => CurrentPeriodMetricsDto
  })
  @ValidateNested()
  @Type(() => CurrentPeriodMetricsDto)
  currentPeriodMetrics: CurrentPeriodMetricsDto;
}