{{- if .Values.configData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "campaign-management-service.fullname" . }}-config
  labels:
    {{- include "campaign-management-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}