import { ApiProperty } from '@nestjs/swagger';
import { IsArray, IsDate, IsNumber, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
// Assuming AppCommissionDetailRO will be in a separate file as per SDS structure.
// For the purpose of this generation, we'll assume it will be available.
import { AppCommissionDetailRO } from './app-commission-detail.ro';

export class AppCommissionReportRO {
  @ApiProperty({
    description: 'The start date of the reporting period for app commissions.',
    example: '2024-03-01T00:00:00.000Z',
    type: Date,
  })
  @IsDate()
  periodStartDate: Date;

  @ApiProperty({
    description: 'The end date of the reporting period for app commissions.',
    example: '2024-03-31T23:59:59.999Z',
    type: Date,
  })
  @IsDate()
  periodEndDate: Date;

  @ApiProperty({
    description: 'The total sales amount generated by all apps through the platform during the reporting period.',
    example: 250000.50,
  })
  @IsNumber()
  totalAppSales: number;

  @ApiProperty({
    description: 'The total amount of commissions earned by the platform from app sales during the reporting period.',
    example: 25000.05,
  })
  @IsNumber()
  totalCommissionsEarned: number;

  @ApiProperty({
    description: 'A detailed breakdown of commissions earned, potentially grouped by individual apps or other criteria.',
    type: () => [AppCommissionDetailRO],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AppCommissionDetailRO)
  commissionDetailsByApp: AppCommissionDetailRO[];
}