import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { ValidateNested, IsArray } from 'class-validator';
import { TopAffiliatePerformanceDto } from './top-affiliate-performance.dto';

export class DashboardMetricsResponseDto {
  @ApiProperty({
    description: 'Total number of affiliates registered with the merchant.',
    example: 250,
  })
  totalAffiliates: number;

  @ApiProperty({
    description: 'Number of currently active affiliates.',
    example: 180,
  })
  activeAffiliates: number;

  @ApiProperty({
    description: 'Number of affiliate applications pending approval.',
    example: 15,
  })
  pendingApplications: number;

  @ApiProperty({
    description: 'Total conversions attributed to affiliates in the last 30 days.',
    example: 1200,
  })
  totalConversionsLast30Days: number;

  @ApiProperty({
    description: 'Total sales volume generated by affiliates in the last 30 days.',
    example: 60000.00,
  })
  totalSalesVolumeLast30Days: number;

  @ApiProperty({
    description: 'Total commissions paid to affiliates in the last 30 days.',
    example: 6000.00,
  })
  totalCommissionsPaidLast30Days: number;

  @ApiProperty({
    description: 'Total commissions currently pending payout.',
    example: 2500.00,
  })
  totalCommissionsPending: number;

  @ApiProperty({
    description: 'List of top performing affiliates (e.g., top 5).',
    type: () => [TopAffiliatePerformanceDto],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TopAffiliatePerformanceDto)
  topPerformingAffiliates: TopAffiliatePerformanceDto[];
}