import { ApiProperty } from '@nestjs/swagger';

export class TopAffiliatePerformanceDto {
  @ApiProperty({
    description: 'Unique identifier of the affiliate.',
    example: 'aff_a1b2c3d4e5',
  })
  affiliateId: string;

  @ApiProperty({
    description: "Name of the affiliate.",
    example: 'SuperStar Affiliate',
  })
  affiliateName: string;

  @ApiProperty({
    description: 'Total number of conversions generated by the affiliate.',
    example: 150,
  })
  conversions: number;

  @ApiProperty({
    description: 'Total sales volume generated by the affiliate.',
    example: 7500.50,
  })
  salesVolume: number;

  @ApiProperty({
    description: 'Total commissions earned by the affiliate.',
    example: 750.05,
  })
  earnedCommissions: number;
}